name: npm-publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      # - run: npm i -g npm@next-7
      # - run: npm ci
      
      - run: git config --global user.name "GitHub CI/CD"
      - run: git config --global user.email "action@github.com"

      - run: |
          cd submodule
          npm version patch

      # - run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
